name: Merge CSVs

on:
  push:
    paths:
      - 'Csv/**'
      - '.github/workflows/merge.yml'
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run Merge Script
        run: node merge_csv.js

      - name: Commit and Push merged CSV
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data_*.csv
          git commit -m "Auto-merge CSV files" || exit 0
          git push
